// src/generic-components/NumericInput.svelte
<script lang="ts">
    import { NumericInputState } from "./NumericInput";

    export let inputAttributes: svelte.JSX.HTMLProps<HTMLElement> | undefined;
    export let messageAttributes: svelte.JSX.HTMLProps<HTMLElement> | undefined;
    export let placeholder: string | undefined;
    export let disabled: boolean | undefined;
    export let modelState: number | undefined;
    export let inputState: NumericInputState;
    export let onChange: (newVal: string) => void;
    export let onBlur: () => void;

</script>

<input
    {...inputAttributes ?? {}}
    class={inputAttributes?.class ?? ""}
    class:invalid={!inputState.isValid}
    value={inputState.currentUnsavedValue ?? modelState?.toString() ?? ""}
    {placeholder}
    {disabled}
    on:change={(e) => onChange(e.currentTarget.value)}
    on:blur={(e) => onBlur()}
/>

{#if inputState.message}
    <div {...messageAttributes ?? {}}>
        {inputState.message}
    </div>
{/if}

<style>
</style>

// src/generic-components/NumericInput.Component.tsx
import { JSX, Show } from "solid-js";
import { NumericInputState } from "./NumericInput";

export function NumericInputComponent(props: {
    inputAttributes?: JSX.HTMLAttributes<HTMLElement>,
    messageAttributes?: JSX.HTMLAttributes<HTMLElement>,
    inputState: NumericInputState,
    placeholder?: string,
    disabled?: boolean,
    modelState: number,
    onChange: (newVal: string) => void,
    onBlur: () => void,
}){

return <>
    <input
        {...props.inputAttributes}
        classList={{
            invalid: !props.inputState.isValid
        }}
        value={props.inputState.currentUnsavedValue ?? props.modelState?.toString() ?? ""}
        placeholder={props.placeholder}
        disabled={props.disabled}
        onChange={(e) => props.onChange(e.currentTarget.value)}
        onBlur={(e) => props.onBlur()}
    ></input>
    <Show
        when={props.inputState.message} 
        keyed={true} 
        children={undefined}    
    >
        <div {...props.messageAttributes}>
            {props.inputState.message}
        </div>
    </Show>
</>;
}
