// src/generic-components/NumericInput.component.tsx
import React from "react";
import { NumericInputState } from "./NumericInput";

type NumericInputProps =
    {
        inputAttributes?: React.HTMLAttributes<HTMLElement>,
        messageAttributes?: React.HTMLAttributes<HTMLElement>,
        placeholder?: string | undefined,
        disabled?: boolean,
        modelState: number | undefined,
        inputState: NumericInputState,
        onChange: (newVal: string) => void,
        onBlur: () => void
    };

export const NumericInput = (props: NumericInputProps) => {

        return <>
            <input
                {...(props.inputAttributes ?? {})}
                className={(props.inputAttributes?.className ?? '') + (props.inputState.isValid ? '' : ' invalid')}
                value={props.inputState.currentUnsavedValue ?? props.modelState?.toString() ?? ''}
                placeholder={props.placeholder}
                disabled={props.disabled}
                onChange={(e) => props.onChange(e.target.value)}
                onBlur={(e) => props.onBlur()}
            />

            {
                props.inputState.message &&
                <div
                    {...(props.messageAttributes ?? {})}>
                    {props.inputState.message}
                </div>
            }
        </>
    };

// src/generic-components/NumericInput.svelte
<script lang="ts">
    import { NumericInputState } from "./NumericInput";

    export let inputAttributes: svelte.JSX.HTMLProps<HTMLElement> | undefined;
    export let messageAttributes: svelte.JSX.HTMLProps<HTMLElement> | undefined;
    export let placeholder: string | undefined;
    export let disabled: boolean | undefined;
    export let modelState: number | undefined;
    export let inputState: NumericInputState;
    export let onChange: (newVal: string) => void;
    export let onBlur: () => void;

</script>

<input
    {...inputAttributes ?? {}}
    class={inputAttributes?.class ?? ""}
    class:invalid={!inputState.isValid}
    value={inputState.currentUnsavedValue ?? modelState?.toString() ?? ""}
    {placeholder}
    {disabled}
    on:change={(e) => onChange(e.currentTarget.value)}
    on:blur={(e) => onBlur()}
/>

{#if inputState.message}
    <div {...messageAttributes ?? {}}>
        {inputState.message}
    </div>
{/if}

<style>
</style>
