// src/generic-components/numeric-input/NumericInput.tsx
import { observer } from "mobx-react";
import React from "react";
import { NumericInputVM } from "./NumericInputVM";

type NumericInputProps =
    {
        inputAttributes?: React.HTMLAttributes<HTMLElement>,
        messageAttributes?: React.HTMLAttributes<HTMLElement>,
        placeholder?: string | undefined,
        vm: NumericInputVM
    };

export const NumericInput =
    observer((props: NumericInputProps) => {

        const vm = props.vm;

        return <>
            <input
                {...props.inputAttributes ?? {}}
                className={(props.inputAttributes?.className ?? '') + (vm.isValid ? '' : ' invalid')}
                value={vm.displayedValue}
                placeholder={props.placeholder}
                disabled={vm.disabled}
                onChange={(e) => vm.onChange(e.target.value)}
                onBlur={(e) => vm.onBlur(e.target.value)}
            />

            {
                vm.message &&
                <div
                    {...props.messageAttributes ?? {}}>
                    {vm.message}
                </div>
            }
        </>
    });

// src/generic-components/NumericInput.svelte
<script lang="ts">
    import { NumericInputState } from "./NumericInput";

    export let inputAttributes: svelte.JSX.HTMLProps<HTMLElement> | undefined;
    export let messageAttributes: svelte.JSX.HTMLProps<HTMLElement> | undefined;
    export let placeholder: string | undefined;
    export let disabled: boolean | undefined;
    export let modelState: number | undefined;
    export let inputState: NumericInputState;
    export let onChange: (newVal: string) => void;
    export let onBlur: () => void;

</script>

<input
    {...inputAttributes ?? {}}
    class={inputAttributes?.class ?? ""}
    class:invalid={!inputState.isValid}
    value={inputState.currentUnsavedValue ?? modelState?.toString() ?? ""}
    {placeholder}
    {disabled}
    on:change={(e) => onChange(e.currentTarget.value)}
    on:blur={(e) => onBlur()}
/>

{#if inputState.message}
    <div {...messageAttributes ?? {}}>
        {inputState.message}
    </div>
{/if}

<style>
</style>
