// src/generic-components/select-dropdown/SelectDropdown.tsx
import { observer } from "mobx-react";
import React from "react";

type SelectDropdownProps<T> =
    {
        selectAttributes?: React.HTMLAttributes<HTMLElement>,
        emptyPlaceholder: string,
        vm: {
            availableItems: T[],

            getKeyValue: (item: T) => string,
            getDescription: (item: T) => string,

            disabled?: boolean
        } & ({
            hasEmptyOption: false,
            selectedItem: T,
            handleSelect: (item: T) => void,
        } | {
            hasEmptyOption: true,
            selectedItem: T | undefined,
            handleSelect: (item: T | undefined) => void,
        })
    };


export const SelectDropdown =
    observer(<T extends unknown>(props: SelectDropdownProps<T>) => {

        const vm = props.vm;

        return <select
            {...props.selectAttributes ?? {}}
            disabled={vm.disabled}
            value={vm.selectedItem
                ? vm.getKeyValue(vm.selectedItem)
                : ''}
            onChange={handleSelect}
        >
            {
                vm.hasEmptyOption &&
                <option value={''}>
                    {props.emptyPlaceholder}
                </option>
            }

            {
                vm.availableItems.map(x => {

                    const keyOrValue = vm.getKeyValue(x);
                    const description = vm.getDescription(x);

                    return <option
                        key={keyOrValue}
                        value={keyOrValue}
                    >
                        {description}
                    </option>
                })
            }
        </select>;

        function handleSelect(e: React.ChangeEvent<HTMLSelectElement>) {
            const value = e.target.value

            const selectedItem = vm.availableItems
                .find(i => value === vm.getKeyValue(i));

            // sattisfy compiler
            if (vm.hasEmptyOption === true) {
                vm.handleSelect(selectedItem);
            } else {
                if (selectedItem === undefined) {
                    throw new Error();
                }
                vm.handleSelect(selectedItem);
            }


        }
    });

// src/generic-components/SelectDropdown.svelte
<script lang="ts" context="module">
    export type SelectDropdownProps<T> = {
        selectAttributes?: svelte.JSX.HTMLProps<HTMLElement>;
        getKeyValue?: (item: T) => string;
        getDescription?: (item: T) => string;
        disabled?: boolean;
        availableItems: T[];
    } & (
        | {
              hasEmptyOption: false;
              modelState: T;
              onSelect: (item: T) => void;
          }
        | {
              hasEmptyOption: true;
              emptyPlaceholder: string;
              modelState: T | undefined;
              onSelect: (item: T | undefined) => void;
          }
    );
</script>

<script lang="ts">
    type T = $$Generic;
    export let p: SelectDropdownProps<T>;

    $: getKeyValue = p.getKeyValue ?? ((x: any) => x.toString());
    $: getDescription = p.getDescription ?? ((x: any) => x.toString());

    function handleSelect(value: string) {

        const selectedItem = p.availableItems.find(
            (i) => value === getKeyValue(i)
        );

        // sattisfy compiler
        if (p.hasEmptyOption === true) {
            p.onSelect(selectedItem);
        } else {
            if (selectedItem === undefined) {
                throw new Error();
            }
            p.onSelect(selectedItem);
        }
    }
</script>

<select
    {...p.selectAttributes ?? {}}
    disabled={p.disabled}
    value={p.modelState ? getKeyValue(p.modelState) : ""}
    on:change={(e) => handleSelect(e.currentTarget.value)}
>
    {#if p.hasEmptyOption}
        <option value={""}>
            {p.emptyPlaceholder}
        </option>
    {/if}

    {#each p.availableItems as item (getKeyValue(item))}
        <option value={getKeyValue(item)}>
            {getDescription(item)}
        </option>
    {/each}
</select>;

<style>
</style>
