// src/generic-components/SelectDropdown.component.tsx
import React from "react";

type SelectDropdownProps<T> =
    {
        selectAttributes?: React.HTMLAttributes<HTMLElement>,    
        getKeyValue?: (item: T) => string,
        getDescription?: (item: T) => string,
        disabled?: boolean,
        availableItems: T[],
    }
    & ({
        hasEmptyOption: false,
        modelState: T,
        onSelect: (item: T) => void
    } | {
        hasEmptyOption: true,
        emptyPlaceholder: string,
        modelState: T | undefined,
        onSelect: (item: T | undefined) => void
    });


export const SelectDropdown = <T extends unknown>(props: SelectDropdownProps<T>) => {

    props = {
        ...props,
        getKeyValue: props.getKeyValue ?? ((x: any) => x.toString()),
        getDescription: props.getDescription ?? ((x: any) => x.toString())
    }

    return <select
        {...props.selectAttributes ?? {}}
        disabled={props.disabled}
        value={props.modelState
            ? props.getKeyValue?.(props.modelState) //for some reason rops.getKeyValue!.(....) does not work with React compiler
            : ''}
        onChange={handleSelect}
    >
        {
            props.hasEmptyOption &&
            <option value={''}>
                {props.emptyPlaceholder}
            </option>
        }

        {
            props.availableItems.map(x => {

                const keyOrValue = props.getKeyValue!(x);
                const description = props.getDescription!(x);

                return <option
                    key={keyOrValue}
                    value={keyOrValue}
                >
                    {description}
                </option>
            })
        }
    </select>;

    function handleSelect(e: React.ChangeEvent<HTMLSelectElement>) {
        const value = e.target.value

        const selectedItem = props.availableItems
            .find(i => value === props.getKeyValue!(i));

        // sattisfy compiler
        if (props.hasEmptyOption === true) {
            props.onSelect(selectedItem);
        } else {
            if (selectedItem === undefined) {
                throw new Error();
            }
            props.onSelect(selectedItem);
        }


    }
};

// src/generic-components/SelectDropdown.svelte
<script lang="ts" context="module">
    export type SelectDropdownProps<T> = {
        selectAttributes?: svelte.JSX.HTMLProps<HTMLElement>;
        getKeyValue?: (item: T) => string;
        getDescription?: (item: T) => string;
        disabled?: boolean;
        availableItems: T[];
    } & (
        | {
              hasEmptyOption: false;
              modelState: T;
              onSelect: (item: T) => void;
          }
        | {
              hasEmptyOption: true;
              emptyPlaceholder: string;
              modelState: T | undefined;
              onSelect: (item: T | undefined) => void;
          }
    );
</script>

<script lang="ts">
    type T = $$Generic;
    export let p: SelectDropdownProps<T>;

    $: getKeyValue = p.getKeyValue ?? ((x: any) => x.toString());
    $: getDescription = p.getDescription ?? ((x: any) => x.toString());

    function handleSelect(value: string) {

        const selectedItem = p.availableItems.find(
            (i) => value === getKeyValue(i)
        );

        // sattisfy compiler
        if (p.hasEmptyOption === true) {
            p.onSelect(selectedItem);
        } else {
            if (selectedItem === undefined) {
                throw new Error();
            }
            p.onSelect(selectedItem);
        }
    }
</script>

<select
    {...p.selectAttributes ?? {}}
    disabled={p.disabled}
    value={p.modelState ? getKeyValue(p.modelState) : ""}
    on:change={(e) => handleSelect(e.currentTarget.value)}
>
    {#if p.hasEmptyOption}
        <option value={""}>
            {p.emptyPlaceholder}
        </option>
    {/if}

    {#each p.availableItems as item (getKeyValue(item))}
        <option value={getKeyValue(item)}>
            {getDescription(item)}
        </option>
    {/each}
</select>;

<style>
</style>
