// src/generic-components/SelectMultiple.component.tsx
import React from "react";

type SelectMultipleProps<T> =
{
    selectAttributes?: React.HTMLAttributes<HTMLElement>,    
    getKeyValue?: (item: T) => string,
    getDescription?: (item: T) => string,
    disabled: boolean,
    availableItems: T[],
    modelState: T[],
    onSelect: (items: T[]) => void
};

export const SelectMultiple = <T extends unknown>(props: SelectMultipleProps<T>) => {

    props = {
        ...props,
        getKeyValue: props.getKeyValue ?? ((x: any) => x.toString()),
        getDescription: props.getDescription ?? ((x: any) => x.toString())
    }

        return <select
            {...props.selectAttributes ?? {}}
            multiple={true}
            disabled={props.disabled}
            value={props.modelState.map(x => props.getKeyValue!(x))}
            onChange={handleSelect}
        >
            {
                props.availableItems.map(x => {

                    const keyOrValue = props.getKeyValue!(x);
                    const description = props.getDescription!(x);

                    return <option
                        key={keyOrValue}
                        value={keyOrValue}
                    >
                        {description}
                    </option>
                })
            }
        </select>;

        function handleSelect(e: React.ChangeEvent<HTMLSelectElement>) {
            const options = e.target.options;
            const values: string[] = [];
            for (var i = 0, l = options.length; i < l; i++) {
                if (options[i].selected) {
                    values.push(options[i].value);
                }
            }

            const selectedItems = props.availableItems
                .filter(i => values.some(v => v === props.getKeyValue!(i)));

            props.onSelect(selectedItems);
        }
    }

// src/generic-components/SelectMultiple.svelte
<script lang="ts">
    type T = $$Generic;

    export let selectAttributes: svelte.JSX.HTMLProps<HTMLElement> = {};
    export let getKeyValue: (item: T) => string = (x: any) => x.toString();
    export let getDescription: (item: T) => string = (x: any) => x.toString();
    export let disabled: boolean = false;
    export let availableItems: T[];
    export let modelState: T[];
    export let onSelect: (items: T[]) => void;

    function handleSelect(options: HTMLOptionsCollection) {
        const values: string[] = [];
        for (var i = 0, l = options.length; i < l; i++) {
            if (options[i].selected) {
                values.push(options[i].value);
            }
        }

        const selectedItems = availableItems.filter((i) =>
            values.some((v) => v === getKeyValue!(i))
        );

        onSelect(selectedItems);
    }
</script>

<select
    {...selectAttributes}
    multiple={true}
    {disabled}
    value={modelState.map((x) => getKeyValue(x))}
    on:change={(e) => handleSelect(e.currentTarget.options)}
>
    {#each availableItems as item (getKeyValue(item))}
        <option value={getKeyValue(item)}>
            {getDescription(item)}
        </option>
    {/each}
</select>

<style>
</style>
