// src/generic-components/select-multiple/SelectMultiple.tsx
import { observer } from "mobx-react";
import React from "react";

type SelectMultipleProps<T> =
    {
        selectAttributes?: React.HTMLAttributes<HTMLElement>,
        vm: {
            availableItems: T[],
            selectedItems: T[],

            getKeyValue: (item: T) => string,
            getDescription: (item: T) => string,

            handleSelect: (items: T[]) => void,
            disabled?: boolean
        }
    };

export const SelectMultiple =
    observer(<T extends unknown>(props: SelectMultipleProps<T>) => {

        const vm = props.vm;

        return <select
            {...props.selectAttributes ?? {}}
            multiple={true}
            disabled={vm.disabled}
            value={vm.selectedItems.map(x => vm.getKeyValue(x))}
            onChange={handleSelect}
        >
            {
                vm.availableItems.map(x => {

                    const keyOrValue = vm.getKeyValue(x);
                    const description = vm.getDescription(x);

                    return <option
                        key={keyOrValue}
                        value={keyOrValue}
                    >
                        {description}
                    </option>
                })
            }
        </select>;

        function handleSelect(e: React.ChangeEvent<HTMLSelectElement>) {
            const options = e.target.options;
            const values: string[] = [];
            for (var i = 0, l = options.length; i < l; i++) {
                if (options[i].selected) {
                    values.push(options[i].value);
                }
            }

            const selectedItems = vm.availableItems
                .filter(i => values.some(v => v === vm.getKeyValue(i)));

            vm.handleSelect(selectedItems);
        }
    });

// src/generic-components/SelectMultiple.svelte
<script lang="ts">
    type T = $$Generic;

    export let selectAttributes: svelte.JSX.HTMLProps<HTMLElement> = {};
    export let getKeyValue: (item: T) => string = (x: any) => x.toString();
    export let getDescription: (item: T) => string = (x: any) => x.toString();
    export let disabled: boolean = false;
    export let availableItems: T[];
    export let modelState: T[];
    export let onSelect: (items: T[]) => void;

    function handleSelect(options: HTMLOptionsCollection) {
        const values: string[] = [];
        for (var i = 0, l = options.length; i < l; i++) {
            if (options[i].selected) {
                values.push(options[i].value);
            }
        }

        const selectedItems = availableItems.filter((i) =>
            values.some((v) => v === getKeyValue!(i))
        );

        onSelect(selectedItems);
    }
</script>

<select
    {...selectAttributes}
    multiple={true}
    {disabled}
    value={modelState.map((x) => getKeyValue(x))}
    on:change={(e) => handleSelect(e.currentTarget.options)}
>
    {#each availableItems as item (getKeyValue(item))}
        <option value={getKeyValue(item)}>
            {getDescription(item)}
        </option>
    {/each}
</select>

<style>
</style>
