// src/models/deals/CarModelSelector.component.tsx
import React from "react";
import { useDispatch, useSelector } from "react-redux";
import { SelectDropdown } from "../../generic-components/SelectDropdown.component";
import type { Dispatch, RootState } from "../store";
import { isLoadingAny } from "../../util/isLoadingAny";

export const CarModelsSelector = (props: {
    dealId: number
}) => {

    const dispatch = useDispatch<Dispatch>();

    const dealState = useSelector((state: RootState) =>
        state.deals.deals.find(x => x.businessParams.dealId === props.dealId))!;

    const isLoading = isLoadingAny(dealState.isLoadingItemized);

    return <>
        {
            dealState.isLoadingItemized.carModelsAvailable
                ? <div className='car-model-selector-select'>Loading</div>
                : <SelectDropdown
                    selectAttributes={{ className: 'car-model-selector-select' }}
                    emptyPlaceholder='Please select model'

                    hasEmptyOption={true}
                    availableItems={dealState.carModelsAvailable}
                    modelState={dealState.businessParams.carModelSelected}
                    getKeyValue={(item) => item.id.toString()}
                    getDescription={(item) => item.description}
                    disabled={isLoading
                                || dealState.businessParams.isDealFinalized}
                    onSelect={(item) => dispatch.deals.setInBusinessParams(
                        props.dealId,
                        {
                            carModelSelected: item
                        })}
                />
        }

        <button
            className='car-model-selector-refresh-btn'
            onClick={() => dispatch.deals.reloadAvailableCarModels(dealState.businessParams.dealId)}
            disabled={isLoading || dealState.businessParams.isDealFinalized}
        >
            Refresh available models
        </button>
    </>
};

// src/models/deals/Deal/CarModelSelector.svelte
<!-- <svelte:options immutable={true}/> -->
<script lang="ts">
    import { dealsStore, dealsEffects } from "../deals.store";
    import { approvalsStore } from "../../approval.store";
    import { clockStore } from "../../clock.store";
    import { computeDealDerrivations } from "../../deals/Deal/Deal";
    import SelectDropdown from "../../../generic-components/SelectDropdown.svelte";

    export let dealId: number;

    $: dealState = computeDealDerrivations(
        $dealsStore,
        $approvalsStore,
        $clockStore,
        dealId
    );

    $: currentDate = $clockStore.currentDate;
</script>

{#if dealState.deal.isLoadingItemized.carModelsAvailable}
    <div class="car-model-selector-select">Loading</div>
{:else}
    <SelectDropdown
        selectAttributes={{ class: "car-model-selector-select" }}
        emptyPlaceholder="Please select model"
        hasEmptyOption={true}
        availableItems={dealState.deal.carModelsAvailable}
        modelState={dealState.deal.businessParams.carModelSelected}
        getKeyValue={(item) => item.id.toString()}
        getDescription={(item) => item.description}
        disabled={dealState.isLoadingAny ||
            dealState.deal.businessParams.isDealFinalized}
        onSelect={(item) =>
            dealsStore.setInBusinessParams(dealId, {
                carModelSelected: item,
            })}
    />
{/if}

<button
    class="car-model-selector-refresh-btn"
    on:click={() =>
        dealsEffects.reloadAvailableCarModels(
            dealsStore,
            dealState.deal.businessParams.dealId
        )}
    disabled={dealState.isLoadingAny ||
        dealState.deal.businessParams.isDealFinalized}
>
    Refresh available models
</button>

<style>
</style>
