// src/models/deals/Deal/InsurancePlanSelector.svelte
<!-- <svelte:options immutable={true}/> -->
<script lang="ts">
    import { dealsStore, dealsEffects } from "../deals.store";
    import { approvalsStore } from "../../approval.store";
    import { clockStore } from "../../clock.store";
    import { computeDealDerrivations } from "../../deals/Deal/Deal";
    import SelectMultiple from "../../../generic-components/SelectMultiple.svelte";

    export let dealId: number;

    $: dealState = computeDealDerrivations(
        $dealsStore,
        $approvalsStore,
        $clockStore,
        dealId
    );

    $: currentDate = $clockStore.currentDate;
</script>

{#if dealState.deal.isLoadingItemized.insurancePlansAvailable}
    <div class="insurance-plan-selector-select">Loading</div>
{:else}
    <SelectMultiple
        selectAttributes={{ class: "insurance-plan-selector-select" }}
        availableItems={dealState.deal.insurancePlansAvailable}
        modelState={dealState.deal.businessParams.insurancePlansSelected}
        disabled={dealState.isLoadingAny}
        getKeyValue={(item) => item.type.toString()}
        getDescription={(item) => item.description}
        onSelect={(items) =>
            dealsStore.setInBusinessParams(dealId, {
                insurancePlansSelected: items,
            })}
    />
{/if}

<button
    class="insurance-plan-selector-refresh-btn"
    on:click={() =>
        dealsEffects.reloadAvailableInsurancePlans(dealsStore, dealId)}
    disabled={dealState.isLoadingAny ||
        dealState.deal.businessParams.isDealFinalized}
>
    Refresh available plans
</button>

<style>
</style>

// src/models/deals/Deal/InsurancePlanSelector.component.tsx
import React from "react";
import { useDispatch, useSelector } from "react-redux";
import { SelectMultiple } from "../../../generic-components/SelectMultiple.component";
import type { Dispatch, RootState } from "../../store";
import { getCachedSelectorDealDerrivations } from "./Deal";

export const InsurancePlanSelector = (props:{
    dealId: number
}) => {

    const dispatch = useDispatch<Dispatch>();

    const dealState = useSelector((state: RootState) => getCachedSelectorDealDerrivations(props.dealId)(state));

    return <>
        {dealState.deal.isLoadingItemized.insurancePlansAvailable
            ? <div className='insurance-plan-selector-select'>Loading</div>
            : <SelectMultiple
                selectAttributes={{ className: 'insurance-plan-selector-select' }}
                availableItems={dealState.deal.insurancePlansAvailable}
                modelState={dealState.deal.businessParams.insurancePlansSelected}
                disabled={dealState.isLoadingAny}
                getKeyValue={(item) => item.type.toString()}
                getDescription={(item) => item.description}
                onSelect={(items) => dispatch.deals.setInBusinessParams(props.dealId,
                    { insurancePlansSelected: items })}
            />
        }
        <button
            className='insurance-plan-selector-refresh-btn'
            onClick={() => dispatch.deals.reloadAvailableInsurancePlans(props.dealId)}
            disabled={dealState.isLoadingAny || dealState.deal.businessParams.isDealFinalized}
        >
            Refresh available plans
        </button>
    </>
}
