// src/app/deals/Deal/InsurancePlanSelector.component.tsx
import { Show } from "solid-js";
import { SelectMultiple } from "../../../generic-components/SelectMultiple.component";

import { DealVM } from "./Deal.vm";

export const InsurancePlanSelector = (props:{
    vm: DealVM
}) => {

    return <>
        <Show
            when={!props.vm.state.activeFlows["loading:insurance-plans"]}
            fallback={<div class='insurance-plan-selector-select'>Loading</div>}
        >
            <SelectMultiple
                selectAttributes={{ class: 'insurance-plan-selector-select' }}
                availableItems={props.vm.state.insurancePlansAvailable}
                vm={props.vm.subVMS.insurancePlansSelected}
                disabled={props.vm.derivedState.isLoading()
                            || props.vm.state.businessParams.isDealFinalized}
                getItemId={(item) => item.type.toString()}
                getItemDescription={(item) => item.description}
                getModelId={(model) => model.type.toString()}
            />
        </Show>
        <button
            class='insurance-plan-selector-refresh-btn'
            onClick={() => props.vm.reloadAvailableInsurancePlans()}
            disabled={props.vm.derivedState.isLoading() || props.vm.state.businessParams.isDealFinalized}
        >
            Refresh available plans
        </button>
    </>
}

// src/models/deals/Deal/InsurancePlanSelector.component.tsx
import React from "react";
import { useDispatch, useSelector } from "react-redux";
import { SelectMultiple } from "../../../generic-components/SelectMultiple.component";
import type { Dispatch, RootState } from "../../store";
import { getCachedSelectorDealDerrivations } from "./Deal";

export const InsurancePlanSelector = (props:{
    dealId: number
}) => {

    const dispatch = useDispatch<Dispatch>();

    const dealState = useSelector((state: RootState) => getCachedSelectorDealDerrivations(props.dealId)(state));

    return <>
        {dealState.deal.isLoadingItemized.insurancePlansAvailable
            ? <div className='insurance-plan-selector-select'>Loading</div>
            : <SelectMultiple
                selectAttributes={{ className: 'insurance-plan-selector-select' }}
                availableItems={dealState.deal.insurancePlansAvailable}
                modelState={dealState.deal.businessParams.insurancePlansSelected}
                disabled={dealState.isLoadingAny}
                getKeyValue={(item) => item.type.toString()}
                getDescription={(item) => item.description}
                onSelect={(items) => dispatch.deals.setInBusinessParams(props.dealId,
                    { insurancePlansSelected: items })}
            />
        }
        <button
            className='insurance-plan-selector-refresh-btn'
            onClick={() => dispatch.deals.reloadAvailableInsurancePlans(props.dealId)}
            disabled={dealState.isLoadingAny || dealState.deal.businessParams.isDealFinalized}
        >
            Refresh available plans
        </button>
    </>
}
